# Generated by Django 3.0.3 on 2020-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashierpos',
            name='checkIn',
            field=models.ManyToManyField(blank=True, to='Cashier.InPos'),
        ),
        migrations.AlterField(
            model_name='cashierpos',
            name='checkOut',
            field=models.ManyToManyField(blank=True, to='Cashier.OutPos'),
        ),
    ]
