# Generated by Django 3.0.3 on 2020-07-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cashier', '0002_auto_20200726_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inpos',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='inpos',
            name='unitPrice',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
    ]
